create database littlechat charset=utf8;
create table ChatUser
(
    username  int                      not null
        primary key,
    password  varchar(20)              not null,
    nickname  varchar(20) default '佚名' not null,
    sex       char        default 'm'  not null,
    age       int                      null,
    image     varchar(100)             null,
    signature varchar(200)             null
)
    comment '存储用户信息的表';

INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10000, 'DK0Qs1eoxm813W', 'Latoya73', 'm', 91, 'C:\\Inetpub\\Products\\Business\\Sales\\pvp.svg', 'Mike like sports. Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10001, 'TQ1jDrU0n7E4', 'Casey26', 'f', 92, 'D:\\Inetpub\\Test\\Sales\\Products\\Red Gate\\Business\\les.jpg', 'I watches football. Mike loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10002, 'PY2F0644Dd28495k', 'Lakeisha', 'f', 28, 'X:\\Windows\\Red Gate\\Test\\SQL Compare\\Sales\\Red Gate\\uhnwu.png', 'Mike watches football. Mike loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10003, 'P61qZfJMiL', 'Colleen8', 'm', 2, null, 'Mike watches football. Rudi loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10004, 'FqHjHDDOMa32UDNNJ46E', 'Alice8', 'f', 80, 'Z:\\Win\\Products\\Sales\\Test\\Products\\Builds\\webi.bmp', 'I loves flowers. Mike loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10005, '6xsc4I6J8iULBd', 'Bernard936', 'm', 15, 'P:\\Program\\Red Gate\\Builds\\Builds\\Builds\\Builds\\jpd.gif', 'Rudi watches football. Mike like swimming. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10006, 'SvDPMC6BPC16H5', 'Howard2', 'm', 42, null, 'Mike like swimming. Mike loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10007, 'jOGAvNQYWUv', 'Hector93', 'f', 0, 'X:\\Program Files\\Test\\Products\\Products\\Sales\\Products\\ter.gif', 'Mike loves flowers. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10008, 'LWX1TLZcPOR8gGsiP3bL', 'Vernon', 'm', 36, 'R:\\Win\\Red Gate\\Sales\\Temp\\Sales\\Test\\pvu.bmp', 'Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10009, 'JM26sTxPQ1TiW6Xf710J', 'Mike8', 'm', 82, 'U:\\Win\\Red Gate\\Temp\\Products\\vst.svg', 'I loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10010, '7sDtBIrlK7J', 'Marissa', 'f', 64, 'A:\\Program\\Products\\Business\\lypyj.gif', 'Mike watches football. Mike loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10011, 'qVUA04HYJb7Oyu37', 'Ruby', 'm', 75, 'V:\\Program Files\\Products\\Test\\Products\\Temp\\Red Gate\\fps.svg', 'I watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10012, 'GQ5o2XST2EL75631X2GI', 'Joni', 'm', 45, 'U:\\Inetpub\\Test\\Temp\\SQL Compare\\Red Gate\\Sales\\tdpv.svg', 'Mike watches football. Rudi loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10013, 'JV732BR1Peb', 'Duane', 'm', 81, 'O:\\Windows\\Products\\Test\\SQL Prompt\\Products\\Builds\\obf.gif', 'Rudi like sports. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10014, 'XL8CF43VkR4', 'Harry07', 'm', 42, 'M:\\Inetpub\\Red Gate\\Sales\\Temp\\Sales\\Builds\\hju.jpg', 'Mike like swimming. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10015, '5rPj9RGL60qIU143o', 'Luz1', 'f', 89, 'K:\\Windows\\Test\\Products\\Test\\Temp\\Red Gate\\jjp.gif', 'Mike watches football. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10016, 'TOT8j6424FYj80', 'Salvatore', 'm', 78, 'R:\\Windows\\Products\\Builds\\Red Gate\\Products\\Red Gate\\fds.svg', 'Rudi watches football. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10017, 'UD7T31Tf9B7qX', 'Byron', 'f', 35, 'J:\\Document and Settings\\Products\\Temp\\Test\\Test\\Red Gate\\dhcy.png', 'Mike like swimming. Mike loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10018, '1on6qVHEjM', 'Sammy632', 'f', 49, 'J:\\Windows\\Sales\\Red Gate\\Business\\Products\\Test\\xxs.bmp', 'Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10019, 'n7BOjWwC1gG6Hw', 'Anthony', 'f', 57, 'V:\\Inetpub\\Business\\SQL Data pattern\\eyi.gif', 'Rudi like sports. I like sports. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10020, 'DZ9Y37hMSx', 'Sarah', 'f', 84, 'O:\\Document and Settings\\Test\\Business\\Products\\Red Gate\\SQL Refactor\\eih.png', 'I watches football. Mike like swimming. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10021, 'MyglMCDWWUJ18L', 'Gavin2', 'f', 90, 'N:\\Inetpub\\Red Gate\\Red Gate\\Test\\Business\\SQL Compare\\gtxt.jpg', 'Mike watches football. Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10022, '5ZGJnF31Uu5NL', 'Candice', 'f', 87, 'W:\\Program\\Products\\SQL Data Compare\\Red Gate\\Test\\wyg.png', 'Mike watches football. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10023, 'GVB80PhCT35J686', 'Terrell984', 'm', 15, 'N:\\Document and Settings\\Products\\Products\\Builds\\Red Gate\\qpy.gif', 'Mike watches football. I watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10024, 'D3BAHimp71ycKVM035V9', 'Travis9', 'm', 45, 'W:\\Inetpub\\Products\\Red Gate\\Business\\cwn.bmp', 'I watches football. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10025, 'lTOZxFBjKSBN', 'Derek', 'm', 56, null, 'Mike like swimming. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10026, 'nUN6nQsJxHKY3mYrT1LW', 'Guy', 'm', 83, 'E:\\Inetpub\\Red Gate\\Business\\Red Gate\\Red Gate\\SQL Prompt\\zcgu.svg', 'Mike loves flowers. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10027, 'tN3AgJ1IP2415uVcoyhI', 'Kelley', 'f', 34, 'T:\\Document and Settings\\SQL Compare\\Temp\\Products\\vro.svg', 'I watches football. Mike like swimming. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10028, 'mwnSBHT25E6M', 'Cara', 'm', 41, 'N:\\Document and Settings\\Red Gate\\Temp\\Temp\\Products\\Red Gate\\htxkz.png', 'Mike watches football. Rudi like sports. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10029, 'dMlhL6K9u1', 'Charles34', 'm', 72, 'B:\\Inetpub\\Red Gate\\Red Gate\\Test\\kbwsq.gif', 'Mike like swimming. Rudi loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10030, 'WpMvfMOhcCl', 'Chris', 'f', null, 'B:\\Win\\Products\\Builds\\Test\\xqb.svg', 'Rudi watches football. Mike like swimming. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10031, '4t3QOf804I33M62', 'Freddie897', 'f', 45, 'O:\\Program\\Red Gate\\Temp\\Test\\SQL Compare\\Builds\\fry.gif', 'Rudi watches football. I like swimming. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10032, 'JtfLLNS0QLKA', 'Jennifer29', 'f', 59, 'E:\\Inetpub\\Products\\Business\\Products\\Temp\\Red Gate\\xwn.svg', 'Mike like swimming. Mike like swimming. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10033, 'b4cCsjstdIQ5', 'Monte', 'f', null, 'E:\\Inetpub\\Builds\\Temp\\Test\\Sales\\Test\\mjf.svg', 'Rudi loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10034, 'TY1w7tqeze1', 'Jeremiah51', 'm', 99, 'S:\\Win\\Sales\\Products\\Products\\Business\\Products\\eehkw.svg', 'Mike like swimming. Rudi like sports. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10035, 'X6S2MHpXwgBto', 'Cynthia2', 'f', 50, null, 'I loves flowers. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10036, 'pWO5F34XhI', 'Gilbert3', 'f', 86, 'B:\\Win\\Products\\Red Gate\\SQL Compare\\Products\\Red Gate\\pptp.jpg', null);
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10037, 'V1DbLC60SH5Byk8', 'Bethany', 'f', 83, 'I:\\Document and Settings\\Sales\\Sales\\Business\\Test\\Products\\crogf.png', 'Mike loves flowers. Mike loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10038, 'FJzPrFK0hF6', 'Lonnie', 'f', 47, 'D:\\Inetpub\\Red Gate\\Red Gate\\Red Gate\\Builds\\Temp\\xyrv.gif', 'Mike like sports. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10039, '3Y7G1MA6WZv', 'Terri5', 'm', 66, 'W:\\Program Files\\SQL Prompt\\Temp\\SQL Prompt\\Red Gate\\Builds\\mfinb.gif', 'Rudi loves flowers. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10040, 'IDHW6UGIVb8LU', 'Candice', 'm', 63, 'Q:\\Win\\Red Gate\\Test\\Business\\Red Gate\\Test\\buwhj.svg', null);
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10041, 'I7MY5yK1Yy43ISW', 'Ashley', 'f', null, 'S:\\Document and Settings\\Test\\Red Gate\\Test\\Red Gate\\hwu.bmp', 'Rudi loves flowers. Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10042, 'VB8kC6vwRwq', 'Darrick7', 'f', 98, null, 'I watches football. Rudi like sports. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10043, '3N3OH9F40vF3C33L', 'Mindy856', 'f', 84, 'M:\\Program\\Red Gate\\SQL Prompt\\fbram.png', 'Mike loves flowers. I loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10044, 'DWB2XX9g8BDT4', 'Jerome4', 'm', 9, 'X:\\Win\\Temp\\Test\\Red Gate\\Red Gate\\Products\\fvu.svg', 'I watches football. Mike like swimming. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10045, 'Gots4MB8nfI68M88QITW', 'Craig', 'f', 30, 'G:\\Document and Settings\\Products\\Products\\Red Gate\\Sales\\Products\\qkl.svg', 'I watches football. Mike like sports. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10046, '75dOAiRbDfH6HjG', 'Chanda', 'm', 79, 'Q:\\Win\\Red Gate\\Test\\Temp\\Test\\Products\\ojqt.gif', 'Mike watches football. Rudi like sports. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10047, 'aQ7D8XFHmMkS', 'Mickey6', 'm', 38, 'J:\\Document and Settings\\Red Gate\\Red Gate\\Sales\\Builds\\Sales\\bjbz.jpg', 'I loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10048, 'Su2JqtV0XDNU0rqW0J6e', 'Brad', 'm', 41, 'U:\\Document and Settings\\Builds\\Red Gate\\Business\\Products\\Business\\tpn.png', 'I loves flowers. I watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10049, '4TdfTxSq9j', 'Lillian6', 'f', 68, 'Y:\\Windows\\Red Gate\\SQL Data Compare\\Products\\Red Gate\\Sales\\kjd.svg', 'Mike like swimming. Rudi loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10050, 'WLhR08JcA4', 'Alexander2', 'f', 79, 'P:\\Inetpub\\Products\\xqo.svg', 'Mike like swimming. I watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10051, 'd32VtXrP66', 'Betsy', 'f', 45, 'M:\\Document and Settings\\Products\\Test\\SQL Refactor\\Red Gate\\Builds\\nrron.png', 'Mike watches football. Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10052, 'FP77h14nEZ38', 'Ann2', 'm', null, 'Q:\\Windows\\Products\\avkve.jpg', 'Rudi like swimming. Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10053, 'QiKSh6BRWT', 'Jeanette1', 'm', 25, 'Q:\\Windows\\Products\\Red Gate\\Builds\\SQL Prompt\\Test\\iqro.gif', 'Mike watches football. Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10054, 'YqHNRAA6TsR68190r17', 'Tracie778', 'f', null, 'E:\\Inetpub\\Red Gate\\Builds\\Business\\Builds\\Temp\\unfu.jpg', 'Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10055, 'PFT7hiBqQP8R1', 'Esther1', 'm', 15, 'N:\\Document and Settings\\Products\\SQL Prompt\\Products\\SQL Prompt\\Red Gate\\mybmq.png', null);
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10056, '4wmr2E92YYg86jPx2lW5', 'Joann268', 'm', 27, 'S:\\Windows\\Red Gate\\Red Gate\\Builds\\Red Gate\\Test\\atvsy.svg', 'Rudi like swimming. I watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10057, '4NWrWgCBE1H', 'Jesse0', 'f', 98, null, 'Rudi watches football. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10058, '0qB32y7SC16G', 'Marcos', 'f', 8, 'Q:\\Program\\Products\\Business\\Sales\\Business\\Business\\rsv.gif', 'Mike watches football. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10059, 'NDLwQRDhd7qLP', 'Kellie8', 'm', 77, 'F:\\Program Files\\Sales\\Temp\\Builds\\Red Gate\\Red Gate\\igrs.png', 'Mike like swimming. Rudi loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10060, 'HXbj2sx5Xn20', 'Neil9', 'f', 93, 'U:\\Inetpub\\Products\\Red Gate\\Business\\Products\\Test\\fnyy.svg', 'I loves flowers. Mike like swimming. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10061, 'KFDx32yc8D12u', 'Andre', 'f', 94, 'P:\\Document and Settings\\Business\\SQL Refactor\\SQL Refactor\\Business\\Sales\\pemcq.gif', null);
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10062, 'F6hV3GnDeW7G0XC3EEJD', 'Jenny', 'm', 25, 'N:\\Win\\Products\\Sales\\Temp\\Red Gate\\Business\\uhx.png', 'Rudi loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10063, 'uEvXEV26oU99Mk3RZ', 'Damien738', 'm', 54, 'J:\\Program Files\\Products\\Sales\\Red Gate\\Sales\\Temp\\nqc.svg', 'I like sports. I loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10064, 'o11CaKodVE7V149CT5E4', 'Mandi2', 'm', 80, 'V:\\Inetpub\\SQL Prompt\\Red Gate\\Builds\\Test\\Red Gate\\urb.jpg', 'Mike watches football. I like sports. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10065, 'QB812vB4oDXv', 'Alexander311', 'm', 10, 'Q:\\Win\\Business\\Business\\Red Gate\\Builds\\Products\\imsk.svg', 'Mike like swimming. Rudi loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10066, '8K2CW6YQlVxV9G', 'Misty', 'f', 81, 'U:\\Inetpub\\Temp\\SQL Refactor\\Temp\\Temp\\SQL Refactor\\qauhd.bmp', 'I like sports. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10067, 'Ve8nQ37nCyi85', 'Miguel64', 'f', 17, 'L:\\Inetpub\\Builds\\yroia.jpg', 'I watches football. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10068, '6KIUaUQW7sTEWF', 'Lauren7', 'f', 48, 'V:\\Document and Settings\\Red Gate\\Red Gate\\Sales\\Builds\\Red Gate\\zkl.png', 'Mike watches football. Rudi like sports. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10069, 'KzD81blR2SNyRCO47XQ9', 'Jess8', 'f', 73, 'W:\\Program\\Red Gate\\Business\\Test\\Business\\Business\\una.svg', 'Rudi loves flowers. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10070, 'Y8h4xEFiq78', 'Anna', 'f', 43, null, 'I watches football. Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10071, 'RJ7k3F58ygY', 'Darin', 'm', 30, 'I:\\Inetpub\\Business\\Temp\\Temp\\hgs.bmp', 'Rudi watches football. I like sports. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10072, 'deU48kN6WItOMah693e3', 'Deanna', 'm', 64, 'F:\\Program Files\\Business\\SQL Prompt\\Business\\Builds\\SQL Compare\\rbzk.svg', 'Rudi watches football. Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10073, 'VtMWBIfD37xJ', 'Alex', 'f', 29, 'F:\\Document and Settings\\Products\\Red Gate\\Products\\SQL Compare\\Red Gate\\ghy.jpg', 'Rudi watches football. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10074, 'MtQJSi5Y4tE28', 'Kristy4', 'm', 85, 'X:\\Document and Settings\\Red Gate\\Temp\\SQL Refactor\\kdbdo.png', null);
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10075, 'YQB4W25SFS6', 'Dominic', 'm', 27, 'J:\\Document and Settings\\Business\\Temp\\Red Gate\\Products\\Temp\\wfito.png', null);
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10076, 'S2Qa6HNE72741CRL7fd2', 'Kendall', 'f', 28, 'D:\\Inetpub\\Red Gate\\Test\\Test\\zbp.svg', 'Mike watches football. Mike loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10077, 'krd5YLtRjh66', 'Scottie6', 'm', 58, 'E:\\Windows\\Business\\Products\\Temp\\Red Gate\\Business\\rknj.jpg', 'Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10078, 'T0XWCxLCKWWD', 'Kenya', 'm', 38, 'X:\\Inetpub\\Business\\SQL Compare\\Products\\SQL Data pattern\\SQL Refactor\\jnwm.png', 'Rudi watches football. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10079, 'DXiCftfTON2', 'Deborah87', 'm', 50, 'U:\\Document and Settings\\Red Gate\\Red Gate\\Sales\\Sales\\Red Gate\\kte.png', 'Mike like swimming. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10080, 'KI1MFEfdoQvd', 'Ross5', 'm', 69, 'L:\\Program Files\\Red Gate\\Sales\\SQL Compare\\SQL Compare\\SQL Refactor\\gdb.svg', 'Mike like sports. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10081, '40SCKyJbUDe44', 'Brandie14', 'f', null, 'N:\\Windows\\Red Gate\\Test\\Sales\\Test\\Products\\dhegi.jpg', 'I watches football. I like sports. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10082, '34Fdwl6j3S', 'Jon65', 'm', 20, 'U:\\Windows\\Business\\SQL Refactor\\Sales\\SQL Compare\\Red Gate\\hsrho.png', 'Rudi watches football. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10083, '5w8rdQx2KWb6OYC75E0N', 'Brandie1', 'f', 100, 'F:\\Program\\Business\\Red Gate\\Sales\\Temp\\Business\\iug.svg', 'I loves flowers. Rudi like sports. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10084, 'RE01O92W9X2', 'Latonya9', 'f', 35, null, 'Mike watches football. Rudi loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10085, '1t6EuP88VpG', 'Saul3', 'f', 56, 'G:\\Inetpub\\Sales\\Products\\Red Gate\\Business\\mvzou.svg', 'Rudi like swimming. Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10086, 'RuGGp1Dhrk6', 'Kenny', 'f', 20, 'O:\\Inetpub\\Products\\lzj.gif', 'Rudi like swimming. I loves flowers. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10087, 'QG7B2PWg0VF7m4D', 'Aimee347', 'f', null, 'F:\\Inetpub\\Products\\Test\\Business\\Temp\\Products\\sck.png', 'Mike like sports. Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10088, 'E11EqICKcKSE2c', 'Melissa', 'f', 86, 'X:\\Program\\Products\\Business\\Sales\\Red Gate\\Red Gate\\ejzcy.svg', 'Rudi loves flowers. Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10089, '7RtJNiPD7X87586jHLCb', 'Jocelyn2', 'f', 7, 'K:\\Inetpub\\Products\\Business\\Products\\ibwk.jpg', null);
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10090, 's87cnX1jwu', 'Claude', 'f', 26, 'H:\\Win\\Temp\\xyi.png', null);
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10091, '5WnvS3DSmAC', 'Vicki6', 'f', 28, 'O:\\Inetpub\\Business\\Business\\Builds\\Sales\\Red Gate\\vlxj.png', 'I watches football. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10092, 'xSLPRIiHGL7EZ3', 'Penny2', 'f', 96, 'H:\\Windows\\Test\\Products\\Builds\\Business\\Red Gate\\ntp.png', 'I loves flowers. Mike like sports. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10093, 'MxGAQ2n1SSMu', 'Yolanda850', 'm', 87, 'R:\\Inetpub\\Products\\Red Gate\\Sales\\gzt.svg', 'Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10094, 'u75SResH7JiE4G', 'Bobbie28', 'm', 82, 'R:\\Windows\\Red Gate\\chja.png', 'Mike loves flowers. Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10095, '30SJ6U6KL2kHV8Y6V6B', 'Dylan5', 'f', 60, 'Y:\\Program Files\\Business\\SQL Refactor\\Red Gate\\Test\\Red Gate\\ofbr.png', 'Rudi watches football. Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10096, '1DU3WGWP6CeFlJwIi6tW', 'Mandy', 'f', 94, 'N:\\Program\\Products\\Red Gate\\qei.jpg', 'I watches football. Rudi watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10097, '4h1R2MiFeeYZ', 'Andres4', 'f', 72, 'O:\\Inetpub\\Red Gate\\Sales\\SQL Compare\\Products\\SQL Compare\\pvq.gif', 'Mike watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10098, 'E7SIgMeNh88l4iI41BNU', 'Lynn', 'm', 69, 'F:\\Inetpub\\Business\\Business\\Red Gate\\Temp\\dmg.svg', 'Mike watches football. I watches football. ');
INSERT INTO LittleChat.ChatUser (username, password, nickname, sex, age, image, signature) VALUES (10099, 'Syf0tjDX557X', 'Kelvin', 'm', 77, 'B:\\Inetpub\\Business\\Red Gate\\Sales\\SQL Prompt\\Red Gate\\ehkkr.bmp', 'Rudi loves flowers. ');